FROM envoyproxy/envoy-dev:latest

RUN apt-get update
RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash -
RUN apt-get -y install nodejs

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .


ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh

EXPOSE 8000
ENTRYPOINT /usr/local/bin/start_service.sh